# -*- coding: utf-8 -*-
"""Gaurav_RystadEnergy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J6Kq3Tw4c3PabGmESz0reo6szgOLg91d

**Importing Pandas**
"""

import pandas as pd

"""**Creating Dataframe**"""

df_list = pd.read_html("https://www.eia.gov/dnav/pet/pet_pnp_inpt_a_epc0_yir_mbbl_m.htm", match="Feb-21")
df = df_list[0]

"""**Removing the empty columns**"""

df.dropna(how='all', axis=1, inplace=True)
df.head(10)

"""**Downloading data to GK file**"""

df.to_csv("rystad.csv", index=False)
